name: NatureEngine
version: '${version}'
main: com.github.cinnaio.natureEngine.NatureEngine
api-version: '1.21'
authors: [ Wynne ]
website: https://github.com/Cinnaio
folia-supported: true
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    CraftEngine:
      load: OMIT
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: OMIT
      required: false
      join-classpath: true
    CustomNameplates:
      load: OMIT
      required: false
      join-classpath: true